[package]
name = "lipid"
version = "0.2.1"
edition = "2024"

[dependencies]
atom = { git = "https://github.com/ippras/atom" }
paste = "1.0.15"
polars = { version = "0.46.0", default-features = false, features = [
    "abs",
    "dtype-categorical",
    "dtype-i8",
    "dtype-struct",
    "dtype-u8",
    "fmt_no_tty",
    "is_in",
    "lazy",
    "list_any_all",
    "list_eval",
    "list_sets",
    "list_to_struct",
    "log",
    "round_series",
    "serde-lazy",
], optional = true }
polars_ext = { git = "https://github.com/kgv/polars_ext", rev = "c86e4e53e63d79f6619e95242324522a252b9643", optional = true }
serde = { version = "1.0.217", features = ["derive", "std"] }

[dev-dependencies]
anyhow = "1.0.95"
lipid = { path = ".", features = ["polars"] }

[features]
default = []
polars = ["dep:polars", "dep:polars_ext"]
