[package]
name = "lipid"
version = "0.0.16"
edition = "2024"

[dependencies]
atom = { git = "https://github.com/ippras/atom" }
paste = "1.0.15"
polars = { version = "0.45.1", default-features = false, features = [
    "abs",
    "dtype-categorical",
    "dtype-i8",
    "dtype-struct",
    "dtype-u8",
    "fmt_no_tty",
    "is_in",
    "lazy",
    "list_any_all",
    "list_eval",
    "list_sets",
    "log",
    "round_series",
    "serde-lazy",
] }
ron = "0.8.1"
serde = { version = "1.0.217", features = ["derive", "std"] }

[dev-dependencies]
anyhow = "1.0.95"

[features]
default = []
