[package]
name = "lipid"
version = "0.2.0"
authors = ["Kazakov Giorgi Vladimirovich", "Sidorov Roman Alexandrovich"]
edition = "2024"

[dependencies]
atom = { git = "https://github.com/ippras/atom" }
fatty_acid_macro = { git = "https://github.com/ippras/fatty_acid_macro" }
polars = { version = "0.46.0", default-features = false, features = [
    "abs",
    "cum_agg",
    "dtype-categorical",
    "dtype-i8",
    "dtype-struct",
    "dtype-u8",
    "fmt_no_tty",
    "is_in",
    "lazy",
    "list_any_all",
    "list_arithmetic",
    "list_eval",
    "list_sets",
    "log",
    "round_series",
    "serde-lazy",
], optional = true }
polars-arrow = "0.46.0"
polars-plan = "0.46.0"
polars_ext = { git = "https://github.com/kgv/polars_ext", optional = true }
rayon = "1.10.0"
serde = { version = "1.0.218", features = ["derive", "std"] }

[dev-dependencies]
anyhow = "1.0.98"
criterion = { version = "0.5.1", features = ["html_reports"] }
lipid = { path = ".", features = ["polars"] }
polars = { version = "0.46.0", default-features = false, features = [
    "abs",
    "cum_agg",
    "dtype-categorical",
    "dtype-i8",
    "dtype-struct",
    "dtype-u8",
    "fmt_no_tty",
    "is_in",
    "lazy",
    "list_any_all",
    "list_arithmetic",
    "list_eval",
    "list_sets",
    "list_to_struct",
    "log",
    "round_series",
    "serde-lazy",
] }

[[bench]]
harness = false
name = "compare"
# name = "expr"

[features]
default = ["atomic", "ecl", "ecn", "indices", "map", "mask", "mass", "select"]

atomic = []
ecl = []
ecn = []
indices = []
map = []
mask = []
mass = []
polars = ["dep:polars", "dep:polars_ext"]
select = []
