[workspace.package]
version = "0.7.1"
edition = "2024"
authors = ["Giorgi Vladimirovich Kazakov", "Roman Alexandrovich Sidorov"]

[package]
name = "lipid"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
polars = { version = "=0.52.0", default-features = false, features = [
    "abs",
    "cum_agg",
    "dtype-i128",
    "dtype-i8",
    "dtype-struct",
    "dtype-u8",
    "fmt_no_tty",
    "is_in",
    "lazy",
    "list_arithmetic",
    "list_eval",
    "log",
    "round_series",
    "serde-lazy",
    #
    "concat_str",
    "strings",
    #
    # "list_sets",
] }
serde = { version = "1.0.228", features = ["derive", "std"], optional = true }

# fatty_acid_macro = { git = "https://github.com/ippras/fatty_acid_macro" }
atom = { git = "https://github.com/ippras/atom" }
fatty_acid_proc_macro = { path = "proc_macro", version = "=0.7.1", optional = true }
polars_ext = { git = "https://github.com/kgv/polars_ext", branch = "0.52" }

[dev-dependencies]
criterion = { version = "0.8.1", features = ["html_reports"] }

[[bench]]
harness = false
name = "compare"
# name = "expr"

[features]
default = [
    "atomic",
    "biodiesel",
    "derive",
    "ecl",
    "ecn",
    "indices",
    "map",
    "mass",
    "select",
]

derive = ["dep:fatty_acid_proc_macro"]
atomic = []
biodiesel = []
ecl = []
ecn = []
indices = []
map = []
mass = []
select = []
