= Lipid library

== Index

`None`:: любое количество связей с неизвестными индексами
`Some(Some(0) (Some(None))`:: одна связь с неизвестным индексом
`Some(Some(NonZeroI8))`:: одна связь с известным индексом

== Identifier

`None`:: любая связь
`S`:: насыщенная связь
`U`:: ненасыщенная связь
`UC`:: ненасыщенная цис связь
`UT`:: ненасыщенная транс связь
`D`:: ненасыщенная двойная связь
`DC`:: ненасыщенная двойная цис связь
`DT`:: ненасыщенная двойная транс связь
`T`:: ненасыщенная тройная связь
`TC`:: ненасыщенная тройная цис связь
`TT`:: ненасыщенная тройная транс связь

FA C*:*
SFA C*:0
MUFA C*:1
PUFA C*:2+

"CCCCCCCCCCCCCCCC(=O)O"
"CCCCCCCCCCCCCCCCCC(=O)O"
Oleic "CCCCCCCCC=CCCCC(=O)O"
Omega -> CCC=CCC=CCC=CCCCCCCCC(=O)O <- Delta

W3 C*:1+[*,D-3]
W6 C*:1+[*,D-6]
W9 C*:1+[*,D-9]

C18:3[D9,D12,D15]

FA    *:*  [{None, None}]
SFA   *:0= [{None, S}]
MUFA 1+:1= [{0, U}, {None, S}]
PUFA 2+:2+ [{0, U}, {0, U}, {None, S}]
     15:1= [{0, S}, {0, S}, {0, S}, {0, S}, {0, S}, {0, S}, {0, S}, {0, S}, {0, S}, {0, S}, {0, S}, {0, S}, {0, S}, {0, S}, {0, U}]
ω3   3+:1+ [{-3, U}, {-2, S}, {-1, S}, {None, None}]
ω6   6+:1+ [{-6, U}, {-5, S}, {-4, S}, {-3, S}, {-2, S}, {-1, S}, {None, None}]
ω9   9+:1+ [{-9, U}, {-8, S}, {-7, S}, {-6, S}, {-5, S}, {-4, S}, {-3, S}, {-2, S}, {-1, S}, {None, None}]

Index
None: any unknown indices
Some(0): one unknown index
Some(x): one known index

PUFA
Series::from_iter([None, 1, None, 1, None])
Series::from_iter([None, U, None, U, None])

== Use

=== Fatty acid

.Linolenic acid
[source]
Omega -> CCC=CCC=CCC=CCCCCCCCC(=O)O <- Delta

- **Decanoic acid, methyl ester**: `InChI=1S/C11H22O2/c1-3-4-5-6-7-8-9-10-11(12)13-2/h3-10H2,1-2H3`
- **9-Octadecynoic acid**: `InChI=1S/C18H32O2/c1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-18(19)20/h2-8,11-17H2,1H3,(H,19,20)`

- **formic acid**: `InChI=1S/CH2O2/c2-1-3/h1H,(H,2,3)`

- **(9Z,12Z)-octadeca-9,12-dienoic acid**: `InChI=1S/C18H32O2/c1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-18(19)20/h6-7,9-10H,2-5,8,11-17H2,1H3,(H,19,20)/b7-6-,10-9-`
- **(9E,12E)-octadeca-9,12-dienoic acid**: `InChI=1S/C18H32O2/c1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-18(19)20/h6-7,9-10H,2-5,8,11-17H2,1H3,(H,19,20)/b7-6+,10-9+`

=== Triacylglycerol

== Build

[source,shell]
cargo build --features=polars
cargo build --features=polars,serde
