use crate::prelude::*;
use std::num::NonZeroI8;

/// [Butyric acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C4: [(Option<Option<NonZeroI8>>, Option<&str>); 3] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
];

/// [Valeric acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C5: [(Option<Option<NonZeroI8>>, Option<&str>); 4] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
];

/// [Caproic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C6: [(Option<Option<NonZeroI8>>, Option<&str>); 5] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
];

/// [Enanthic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C7: [(Option<Option<NonZeroI8>>, Option<&str>); 6] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
];

/// [Caprylic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C8: [(Option<Option<NonZeroI8>>, Option<&str>); 7] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
];

/// [Pelargonic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C9: [(Option<Option<NonZeroI8>>, Option<&str>); 8] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
];

/// [Capric acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C10: [(Option<Option<NonZeroI8>>, Option<&str>); 9] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
];

/// [Undecylic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C11: [(Option<Option<NonZeroI8>>, Option<&str>); 10] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
];

/// [Lauric acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C12: [(Option<Option<NonZeroI8>>, Option<&str>); 11] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
];

/// [Tridecylic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C13: [(Option<Option<NonZeroI8>>, Option<&str>); 12] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
];

/// [Myristic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C14: [(Option<Option<NonZeroI8>>, Option<&str>); 13] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
];

/// [Pentadecylic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C15: [(Option<Option<NonZeroI8>>, Option<&str>); 14] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
];

/// [Palmitic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C16: [(Option<Option<NonZeroI8>>, Option<&str>); 15] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
];

/// [Margaric acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C17: [(Option<Option<NonZeroI8>>, Option<&str>); 16] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
];

/// [Stearic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C18: [(Option<Option<NonZeroI8>>, Option<&str>); 17] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
];

/// [Nonadecylic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C19: [(Option<Option<NonZeroI8>>, Option<&str>); 18] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
];

/// [Arachidic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C20: [(Option<Option<NonZeroI8>>, Option<&str>); 19] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
];

/// [Heneicosylic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C21: [(Option<Option<NonZeroI8>>, Option<&str>); 20] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
];

/// [Behenic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C22: [(Option<Option<NonZeroI8>>, Option<&str>); 21] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
];

/// [Tricosylic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C23: [(Option<Option<NonZeroI8>>, Option<&str>); 22] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
];

/// [Lignoceric acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C24: [(Option<Option<NonZeroI8>>, Option<&str>); 23] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
];

/// [Hyenic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C25: [(Option<Option<NonZeroI8>>, Option<&str>); 24] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
    (Some(NonZeroI8::new(24)), Some(S)),
];

/// [Cerotic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C26: [(Option<Option<NonZeroI8>>, Option<&str>); 25] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
    (Some(NonZeroI8::new(24)), Some(S)),
    (Some(NonZeroI8::new(25)), Some(S)),
];

/// [Carboceric acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C27: [(Option<Option<NonZeroI8>>, Option<&str>); 26] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
    (Some(NonZeroI8::new(24)), Some(S)),
    (Some(NonZeroI8::new(25)), Some(S)),
    (Some(NonZeroI8::new(26)), Some(S)),
];

/// [Montanic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C28: [(Option<Option<NonZeroI8>>, Option<&str>); 27] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
    (Some(NonZeroI8::new(24)), Some(S)),
    (Some(NonZeroI8::new(25)), Some(S)),
    (Some(NonZeroI8::new(26)), Some(S)),
    (Some(NonZeroI8::new(27)), Some(S)),
];

/// [Nonacosylic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C29: [(Option<Option<NonZeroI8>>, Option<&str>); 28] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
    (Some(NonZeroI8::new(24)), Some(S)),
    (Some(NonZeroI8::new(25)), Some(S)),
    (Some(NonZeroI8::new(26)), Some(S)),
    (Some(NonZeroI8::new(27)), Some(S)),
    (Some(NonZeroI8::new(28)), Some(S)),
];

/// [Melissic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C30: [(Option<Option<NonZeroI8>>, Option<&str>); 29] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
    (Some(NonZeroI8::new(24)), Some(S)),
    (Some(NonZeroI8::new(25)), Some(S)),
    (Some(NonZeroI8::new(26)), Some(S)),
    (Some(NonZeroI8::new(27)), Some(S)),
    (Some(NonZeroI8::new(28)), Some(S)),
    (Some(NonZeroI8::new(29)), Some(S)),
];

/// [Henatriacontylic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C31: [(Option<Option<NonZeroI8>>, Option<&str>); 30] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
    (Some(NonZeroI8::new(24)), Some(S)),
    (Some(NonZeroI8::new(25)), Some(S)),
    (Some(NonZeroI8::new(26)), Some(S)),
    (Some(NonZeroI8::new(27)), Some(S)),
    (Some(NonZeroI8::new(28)), Some(S)),
    (Some(NonZeroI8::new(29)), Some(S)),
    (Some(NonZeroI8::new(30)), Some(S)),
];

/// [Lacceroic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C32: [(Option<Option<NonZeroI8>>, Option<&str>); 31] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
    (Some(NonZeroI8::new(24)), Some(S)),
    (Some(NonZeroI8::new(25)), Some(S)),
    (Some(NonZeroI8::new(26)), Some(S)),
    (Some(NonZeroI8::new(27)), Some(S)),
    (Some(NonZeroI8::new(28)), Some(S)),
    (Some(NonZeroI8::new(29)), Some(S)),
    (Some(NonZeroI8::new(30)), Some(S)),
    (Some(NonZeroI8::new(31)), Some(S)),
];

/// [Psyllic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C33: [(Option<Option<NonZeroI8>>, Option<&str>); 32] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
    (Some(NonZeroI8::new(24)), Some(S)),
    (Some(NonZeroI8::new(25)), Some(S)),
    (Some(NonZeroI8::new(26)), Some(S)),
    (Some(NonZeroI8::new(27)), Some(S)),
    (Some(NonZeroI8::new(28)), Some(S)),
    (Some(NonZeroI8::new(29)), Some(S)),
    (Some(NonZeroI8::new(30)), Some(S)),
    (Some(NonZeroI8::new(31)), Some(S)),
    (Some(NonZeroI8::new(32)), Some(S)),
];

/// [Gheddic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C34: [(Option<Option<NonZeroI8>>, Option<&str>); 33] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
    (Some(NonZeroI8::new(24)), Some(S)),
    (Some(NonZeroI8::new(25)), Some(S)),
    (Some(NonZeroI8::new(26)), Some(S)),
    (Some(NonZeroI8::new(27)), Some(S)),
    (Some(NonZeroI8::new(28)), Some(S)),
    (Some(NonZeroI8::new(29)), Some(S)),
    (Some(NonZeroI8::new(30)), Some(S)),
    (Some(NonZeroI8::new(31)), Some(S)),
    (Some(NonZeroI8::new(32)), Some(S)),
    (Some(NonZeroI8::new(33)), Some(S)),
];

/// [Ceroplastic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C35: [(Option<Option<NonZeroI8>>, Option<&str>); 34] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
    (Some(NonZeroI8::new(24)), Some(S)),
    (Some(NonZeroI8::new(25)), Some(S)),
    (Some(NonZeroI8::new(26)), Some(S)),
    (Some(NonZeroI8::new(27)), Some(S)),
    (Some(NonZeroI8::new(28)), Some(S)),
    (Some(NonZeroI8::new(29)), Some(S)),
    (Some(NonZeroI8::new(30)), Some(S)),
    (Some(NonZeroI8::new(31)), Some(S)),
    (Some(NonZeroI8::new(32)), Some(S)),
    (Some(NonZeroI8::new(33)), Some(S)),
    (Some(NonZeroI8::new(34)), Some(S)),
];

/// [Hexatriacontylic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C36: [(Option<Option<NonZeroI8>>, Option<&str>); 35] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
    (Some(NonZeroI8::new(24)), Some(S)),
    (Some(NonZeroI8::new(25)), Some(S)),
    (Some(NonZeroI8::new(26)), Some(S)),
    (Some(NonZeroI8::new(27)), Some(S)),
    (Some(NonZeroI8::new(28)), Some(S)),
    (Some(NonZeroI8::new(29)), Some(S)),
    (Some(NonZeroI8::new(30)), Some(S)),
    (Some(NonZeroI8::new(31)), Some(S)),
    (Some(NonZeroI8::new(32)), Some(S)),
    (Some(NonZeroI8::new(33)), Some(S)),
    (Some(NonZeroI8::new(34)), Some(S)),
    (Some(NonZeroI8::new(35)), Some(S)),
];
