use crate::prelude::*;
use std::num::NonZeroI8;

/// [Palmitoleic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C16DC9: [(Option<Option<NonZeroI8>>, Option<&str>); 15] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DC)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
];

/// [Palmitelaidic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C16DT9: [(Option<Option<NonZeroI8>>, Option<&str>); 15] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DT)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
];

/// [Oleic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C18DC9: [(Option<Option<NonZeroI8>>, Option<&str>); 17] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DC)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
];

/// [Elaidic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C18DT9: [(Option<Option<NonZeroI8>>, Option<&str>); 17] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DT)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
];

/// [Linoleic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C18DC9DC12: [(Option<Option<NonZeroI8>>, Option<&str>); 17] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DC)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(DC)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
];

/// [α-Linolenic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C18DC9DC12DC15: [(Option<Option<NonZeroI8>>, Option<&str>); 17] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DC)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(DC)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(DC)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
];

/// [γ-Linolenic acid, GLA](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C18DC6DC9DC12: [(Option<Option<NonZeroI8>>, Option<&str>); 17] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(DC)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DC)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(DC)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
];

/// [Jacaric acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C18DC8DT10DC12: [(Option<Option<NonZeroI8>>, Option<&str>); 17] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(DC)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(DT)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(DC)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
];

/// [α-Eleostearic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C18DC9DT11DT13: [(Option<Option<NonZeroI8>>, Option<&str>); 17] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DC)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(DT)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(DT)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
];

/// [β-Eleostearic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C18DT9DT11DT13: [(Option<Option<NonZeroI8>>, Option<&str>); 17] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DT)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(DT)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(DT)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
];

/// [Catalpic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C18DT9DT11DC13: [(Option<Option<NonZeroI8>>, Option<&str>); 17] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DT)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(DT)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(DC)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
];

/// [Stearidonic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C18DC6DC9DC12DC15: [(Option<Option<NonZeroI8>>, Option<&str>); 17] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(DC)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DC)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(DC)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(DC)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
];

/// [Gadoleic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C20DC9: [(Option<Option<NonZeroI8>>, Option<&str>); 19] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DC)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
];

/// [Gondoic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C20DC11: [(Option<Option<NonZeroI8>>, Option<&str>); 19] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(DC)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
];

/// [DihomoLinoleic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C20DC11DC14: [(Option<Option<NonZeroI8>>, Option<&str>); 19] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(DC)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(DC)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
];

/// [Bis-homo-α-Linolenic acid, DTTA](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C20DC11DC14DC17: [(Option<Option<NonZeroI8>>, Option<&str>); 19] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(DC)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(DC)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(DC)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
];

/// [Bis-homo-γ-Linolenic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C20DC8DC11DC14: [(Option<Option<NonZeroI8>>, Option<&str>); 19] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(DC)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(DC)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(DC)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
];

/// [Mead Acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C20DC5DC8DC11: [(Option<Option<NonZeroI8>>, Option<&str>); 19] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(DC)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(DC)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(DC)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
];

/// [Arachidonic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C20DC5DC8DC11DC14: [(Option<Option<NonZeroI8>>, Option<&str>); 19] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(DC)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(DC)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(DC)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(DC)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
];

/// [Eicosatetraenoic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C20DC8DC11DC14DC17: [(Option<Option<NonZeroI8>>, Option<&str>); 19] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(DC)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(DC)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(DC)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(DC)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
];

/// [Eicosapentaenoic EPA](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C20DC5DC8DC11DC14DC17: [(Option<Option<NonZeroI8>>, Option<&str>); 19] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(DC)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(DC)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(DC)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(DC)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(DC)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
];

/// [Erucic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C22DC13: [(Option<Option<NonZeroI8>>, Option<&str>); 21] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(DC)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
];

/// [Docosadienoic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C22DC13DC16: [(Option<Option<NonZeroI8>>, Option<&str>); 21] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(DC)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(DC)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
];

/// [Eranthic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C22DC5DC13DC16: [(Option<Option<NonZeroI8>>, Option<&str>); 21] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(DC)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(DC)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(DC)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
];

/// [Adrenic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C22DC7DC10DC13DC16: [(Option<Option<NonZeroI8>>, Option<&str>); 21] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(DC)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(DC)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(DC)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(DC)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
];

/// [DPA](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C22DC7DC10DC13DC16DC19: [(Option<Option<NonZeroI8>>, Option<&str>); 21] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(DC)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(DC)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(DC)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(DC)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(DC)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
];

/// [DHA](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C22DC4DC7DC10DC13DC16DC19: [(Option<Option<NonZeroI8>>, Option<&str>); 21] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(DC)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(DC)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(DC)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(DC)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(DC)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(DC)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
];

/// [Nervonic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C24DC15: [(Option<Option<NonZeroI8>>, Option<&str>); 23] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(DC)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
];

/// [Tetracosadienoic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C24DC15DC18: [(Option<Option<NonZeroI8>>, Option<&str>); 23] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(DC)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(DC)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
];

/// [Tetracosatrienylic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C24DC12DC15DC18: [(Option<Option<NonZeroI8>>, Option<&str>); 23] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(DC)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(DC)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(DC)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
];

/// [Tetracosatetraenylic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C24DC9DC12DC15DC18: [(Option<Option<NonZeroI8>>, Option<&str>); 23] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DC)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(DC)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(DC)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(DC)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
];

/// [Tetracosapentaenylic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C24DC6DC9DC12DC15DC18: [(Option<Option<NonZeroI8>>, Option<&str>); 23] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(DC)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DC)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(DC)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(DC)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(DC)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
];

/// [Tetracosahexaenylic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C24DC6DC9DC12DC15DC18DC21: [(Option<Option<NonZeroI8>>, Option<&str>); 23] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(DC)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(DC)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(DC)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(DC)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(DC)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(DC)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
];

/// [Ximenic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C26DC17: [(Option<Option<NonZeroI8>>, Option<&str>); 25] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(DC)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(S)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
    (Some(NonZeroI8::new(24)), Some(S)),
    (Some(NonZeroI8::new(25)), Some(S)),
];

/// [Lumequeic acid](https://byrdwell.com/Triacylglycerols/FattyAcids.htm)
pub static C30DC21: [(Option<Option<NonZeroI8>>, Option<&str>); 29] = [
    (Some(NonZeroI8::new(1)), Some(S)),
    (Some(NonZeroI8::new(2)), Some(S)),
    (Some(NonZeroI8::new(3)), Some(S)),
    (Some(NonZeroI8::new(4)), Some(S)),
    (Some(NonZeroI8::new(5)), Some(S)),
    (Some(NonZeroI8::new(6)), Some(S)),
    (Some(NonZeroI8::new(7)), Some(S)),
    (Some(NonZeroI8::new(8)), Some(S)),
    (Some(NonZeroI8::new(9)), Some(S)),
    (Some(NonZeroI8::new(10)), Some(S)),
    (Some(NonZeroI8::new(11)), Some(S)),
    (Some(NonZeroI8::new(12)), Some(S)),
    (Some(NonZeroI8::new(13)), Some(S)),
    (Some(NonZeroI8::new(14)), Some(S)),
    (Some(NonZeroI8::new(15)), Some(S)),
    (Some(NonZeroI8::new(16)), Some(S)),
    (Some(NonZeroI8::new(17)), Some(S)),
    (Some(NonZeroI8::new(18)), Some(S)),
    (Some(NonZeroI8::new(19)), Some(S)),
    (Some(NonZeroI8::new(20)), Some(S)),
    (Some(NonZeroI8::new(21)), Some(DC)),
    (Some(NonZeroI8::new(22)), Some(S)),
    (Some(NonZeroI8::new(23)), Some(S)),
    (Some(NonZeroI8::new(24)), Some(S)),
    (Some(NonZeroI8::new(25)), Some(S)),
    (Some(NonZeroI8::new(26)), Some(S)),
    (Some(NonZeroI8::new(27)), Some(S)),
    (Some(NonZeroI8::new(28)), Some(S)),
    (Some(NonZeroI8::new(29)), Some(S)),
];
